#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Huang Junye

# Short bio or description (displayed in the header)
description: Quantum Developer Advocate at IBM Qiskit

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/huangjunye.png

# Includes an icon in the footer for each username you enter
footer-links:
  email: h.jun.ye@gmail.com
  github: HuangJunye
  linkedin:
  rss: # just type anything here for a working RSS icon
  twitter: HuangJunye
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: huangjunye

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-52372886-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://huangjunye.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate-v2

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

permalink: /:year/:month/:title:output_ext

############################################################
# Site configuration for the jekyll-paginate-v2 Gem
pagination:
  
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  title: ':title - Page :num'
  sort_reverse: true
  tag: '' # Optional, the default tag to use, omit to disable
  trail: 
    before: 2
    after: 2

############################################################
